version: "3"
services:
  map-gl-indoor:
    build:
      context: .
      dockerfile: Dockerfile
    image: indoor/map-gl-indoor
    ports:
    - 8888:80
    volumes:
    - ./examples/index.html:/map-gl-indoor/index.html

